### ISSUE TITLE
boba run should run all universes even if some failed

### ISSUE THREAD

**Issue by yyyliu** [uwdata/multiverse-spec#10] opened 2020-06-26 06:16 UTC
When a universe exits with a non-zero status code, it seems the process would stop and subsequent universes will not run. But ideally we want to run every universe the user specifies even if some of the universes fail in the middle. 

To reproduce:
1. Add `exit(1)` on line 16 [here](https://github.com/uwdata/multiverse-spec/blob/4d46ce4d631391b192efc89484f388ce31612343/example/simple/template.py#L16).
2. Run this command `boba run --all --jobs 0 --batch_size 1`

**Comment by AmethystGear** [comment] 2020-06-26 06:59
I thought terminating the multiverse if a process failed was the intended behavior. This is easily fixed by removing this:
```
        for res in r:
            if res[1] != 0:
                pool.terminate() # end computation if one of the processes was unsuccessful
```
from the check_result callback.
this should be fixed in #12

**Closed** 2020-06-27 06:15 UTC
